# Parameters for DQN
BETA1 = 0.5
LEARNING_RATE = 5e-3
BATCH_SIZE = 1
LOCAL_DIMENSION = 3
FULL_DIMENSION = 6

NUM_EPISODES = 100000
NUM_STATES = LOCAL_DIMENSION*LOCAL_DIMENSION
EPISODE_LENGTH = FULL_DIMENSION*FULL_DIMENSION*2

NUM_POSSIBLE_PIXEL_COLORS = 2
